version = 0.1

[default.build.parameters]
parallel = "true"

[default.deploy.parameters]
fail_on_empty_changeset = "false"
resolve_s3 = "true"
capabilities = "CAPABILITY_IAM"

[default.local_start_api.parameters]
warm_containers = "LAZY"

[default.logs.parameters]
start_time = "0mins ago"
tail = "true"